sudo: required
service:
 - docker
before_install:
  - docker build -t hethkar/travis:1.0 .
script:
 - echo "$docker_password" | docker login -u "$docker_username" --password-stdin
 - docker images # to verify image is build or not
 - docker push hethkar/travis:1.0
notifications:
 email:
   recipients:
     - dkrhemanth@gmail.com
   on_success: always
   on_failure: always
